# Lista de Exercícios

In [1]:
import numpy as np
import numpy.linalg as la

### Exercício 1 - Considere o vetor [1, 2, 3, 4, 5], construa um novo vetor com três elementos 0 (zero) entre cada elemento do vetor.

In [2]:
a = np.array([1,2,3,4,5])
np.hstack((a[:,None], np.zeros([5,3], dtype = int))).flatten()[0:-3]

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [3]:
np.insert(a,(1,1,1,2,2,2,3,3,3,4,4,4),[0,0,0,0,0,0,0,0,0,0,0,0])

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [4]:
a = np.array([1, 2, 3, 4, 5])
rep = np.insert(a, np.repeat(a[0:4],3),0)
rep

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [7]:
a = np.array([1,2,3,4,5])

for i in [1,5,9,13]:
    a = np.insert(a, i, [0,0,0])
a

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

In [8]:
np.insert(np.insert(np.insert(np.insert(a,1,[0,0,0]),5,[0,0,0]),9,[0,0,0]),-1,[0,0,0])

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4,
       0, 0, 0, 0, 0, 0, 5])

**Resposta:**

```
array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])
```

### Exercício 2 - Crie uma matriz quadrada de 8 X 8 e preencha com o padrão de tabuleiro de xadrez, utilizando 0 (zero) para casas brancas e 1 (um) para casas pretas.

In [187]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

Checkerboard pattern:


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [13]:
par_0 = np.vectorize(lambda x: 1 if (x%2 == 0) else 0)
array = np.arange(1,65, dtype=int)
array = par_0(array).reshape(8,8)
array[1::2] = np.bitwise_xor(array[1::2], np.ones(8,dtype=int))
array

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [14]:
pares = np.r_[ 4*[0,1] ]      #linhas pares
impares = np.r_[ 4*[1,0] ]    #linhas impares
arr_2 = np.row_stack(4*(pares, impares))

arr_2

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**Resposta:**

```
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])
```

### Exercício 3 - Dado um array de 2 dimensões, como trocar 2 linhas entre si?

In [55]:
arr = np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
arrb = np.roll(arr, 0, axis = 0)
arrb

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
x=0
y=1
arrb[[x,y]] = arrb [[y,x]]
arrb

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
x=2
y=3
arrb[[x,y]] = arrb[[y,x]]
arrb

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [15]:
arr = np.arange(0,25).reshape(5,5)
arr[[0,1],:] = arr[[1,0],:]
arr

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
array_0_1 = arr.copy()
array_0_1[0:2:1] = np.flip(array_0_1[0:2:1],0)
array_0_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr[[0, 1]] = arr[[1, 0]]
arr

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
arr[0:2:1] =arr[-4::-1]
arr

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr[[2, 3]] = arr[[3, 2]]
arr

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

**Resposta:**

array inicial:
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

array com as linhas 0 e 1 trocadas entre si:
```
array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

array com as linhas 2 e 3 trocadas entre si:
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])
```

### Exercício 4 - Dado um array de 2 dimensões, como trocar 2 colunas entre si?

In [119]:
arr = np.arange(0,25).reshape(5,5)
arr[:,[0,1]] = arr[:,[1,0]]
arr

array([[ 1,  0,  2,  3,  4],
       [ 6,  5,  7,  8,  9],
       [11, 10, 12, 13, 14],
       [16, 15, 17, 18, 19],
       [21, 20, 22, 23, 24]])

In [134]:
arr=np.arange(0,25).reshape(5,5)
arr[:,[2,3]] = arr[:,[3,2]]
arr

array([[ 0,  1,  3,  2,  4],
       [ 5,  6,  8,  7,  9],
       [10, 11, 13, 12, 14],
       [15, 16, 18, 17, 19],
       [20, 21, 23, 22, 24]])

**Resposta:**

array inicial:
```
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])
```

array com as colunas 2 e 3 trocadas entre si:
```
array([[ 0,  1,  3,  2,  4],
       [ 5,  6,  8,  7,  9],
       [10, 11, 13, 12, 14],
       [15, 16, 18, 17, 19],
       [20, 21, 23, 22, 24]])
```

### Exercício 5 - Dado o array [1, 2, 3] criar o array [[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [174]:
arr = np.array([1,2,3]).reshape(1,3)
np.array(list(arr)*4).reshape(4,3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [318]:
arr = np.arange(1,4)
arrb = np.lib.stride_tricks.as_strided(arr,(4,3),(0,4))
arrb

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [436]:
arr = np.array([1,2,3])

i=2
while i<5:
    arr = np.insert(arr,[0], [1,2,3], axis = 0).reshape(i,3)
    i+=1
arr    

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [28]:
arr = np.arange(1,4)
np.stack((arr, arr,arr, arr))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [29]:
np.array(list(arr)*4).reshape(4,3)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
np.full((4,3),[1,2,3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [31]:
arr_5 = np.array([1,2,3])
np.tile(arr_5, (4,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

**Resposta:**

```
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])
``` 


### Exercício 6 - Dado o array [1, 2, 3] criar o array [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [39]:
arr = np.array([1,2,3])
np.insert(arr,(0,0,1,1,2,2),[1,1,2,2,3,3]).reshape(3,3)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [32]:
arr_6 = np.array([1,2,3])
np.repeat(arr_6[:,np.newaxis], 3, 1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [33]:
arr = np.arange(1,4)
arr = arr.reshape(3,1)

np.insert(arr,[0,1] ,[[1],[2],[3]], axis=1 )

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [40]:
arr = np.repeat(arr, 3, axis = 0).reshape((3,3))
arr

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [38]:
np.column_stack(np.full((3,3),[1,2,3]))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [42]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [43]:
np.full((3,3),[1,2,3]).transpose()

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

**Resposta:**

```
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])
```

### Exercício 7 - Dado o array [4, 95, 37, 64, 42, 19, 55, 38, 46, 83, 48, 67, 98, 21, 10, 88], obtenha todos os itens que estão entre 35 e 55.

In [57]:
arr = np.array([4,95,37,64,42,19,55,38,46,83,48,67,98,21,10,88])
ind_pos = np.where(np.logical_and(arr>=35, arr<=55))
arrc = (arr[ind_pos])
arrc

array([37, 42, 55, 38, 46, 48])

In [45]:
arr = np.array([4, 95, 37, 64, 42, 19, 55, 38, 46, 83, 48, 67, 98, 21, 10, 88])
res = arr[np.where((arr > 35) & (arr < 56))]
res

array([37, 42, 55, 38, 46, 48])

In [46]:
arr[(arr >= 35) & (arr <= 55)]

array([37, 42, 55, 38, 46, 48])

In [58]:
arr[np.where(np.logical_and(arr >= 35, arr <= 55))]

array([37, 42, 55, 38, 46, 48])

**Resposta:**

```
array([37, 42, 38, 46, 48, 55])
```


### Exercicio 8 - Considere um array com 100 elementos inteiros iniciando em 0. Dado um número randômico positivo e flutuante, descubra qual o elemento do array, mais próximo desse número.

In [50]:
arr = np.arange(0,101)
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [51]:
f = np.random.uniform(0,100)
f
print("Original array:")
print(arr)
print("Value to compare:")
print(f)
index = (np.abs(arr-f)).argmin()
print(arr[index])

Original array:
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
Value to compare:
10.672541745744901
11


In [52]:
elem = np.argmin(np.abs(arr - f))
elem

11

In [55]:
v = arr[min(range(len(arr)), key = lambda i: abs(arr[i]-f))]
v

11

### Exercicio 9 - Dado um array, substitua todos os valores inferiores a 10 por 10 e todos os valores superiores a 30 por 30.

In [59]:
np.random.seed(100)
print('array inicial:\n')
arr = np.random.uniform(1, 50, 30)
print(arr)

arr[arr<10]=10
arr[arr>30]=30
arrb = arr

print('\narray após as substituições:\n')
arrb

array inicial:

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361 22.153505   47.06146116 41.06481956 17.46948556
  9.59511223 19.26877027  1.27873686 13.36889132 39.98746292  1.74749359]

array após as substituições:



array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361,
       22.153505  , 30.        , 30.        , 17.46948556, 10.        ,
       19.26877027, 10.        , 13.36889132, 30.        , 10.        ])

In [60]:
arr[np.where(arr < 10)] = 10
arr[np.where(arr > 30)] = 30
arr

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361,
       22.153505  , 30.        , 30.        , 17.46948556, 10.        ,
       19.26877027, 10.        , 13.36889132, 30.        , 10.        ])

**Resposta**

array inicial:
```
array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361,
       22.153505  , 47.06146116, 41.06481956, 17.46948556,  9.59511223,
       19.26877027,  1.27873686, 13.36889132, 39.98746292,  1.74749359])
```

array após as substituições:
```
array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361,
       22.153505  , 30.        , 30.        , 17.46948556, 10.        ,
       19.26877027, 10.        , 13.36889132, 30.        , 10.        ])
```

### Exercicio 10 - Para calcular o determinante de matrizes de terceira ordem, utiliza-se a chamada regra de Sarrus, que resulta no seguinte cálculo:

$
D\left(\begin{array}{cc} 
a & b & c \\
d & e & f \\
g & h & i
\end{array}\right)
$ = (aei + bfg + cdh) - (afh + bdi + ceg)

### Escreva uma função para calcular o determinante de uma matriz quadrada de ordem 3.

In [83]:
def sarrus(a):
    aei = a[0,0]*a[1,1]*a[2,2]
    bfg = a[0,1]*a[1,2]*a[2,0]
    cdh = a[0,2]*a[1,0]*a[2,1]
    afh = a[0,0]*a[1,2]*a[2,1]
    bdi = a[0,1]*a[1,0]*a[2,2]
    ceg = a[0,2]*a[1,1]*a[2,0]
    D = (aei + bfg + cdh) - (afh + bdi + ceg)
    return D

arr = np.array([1,5,-2,8,3,0,4,-1,2]).reshape(3,3)
sarrus(arr)

-34

In [77]:
def determinant(n):
    return np.linalg.det(n)
arr = np.array([1,5,-2,8,3,0,4,-1,2]).reshape(3,3)
determinant(arr)

-33.99999999999999

In [82]:
def regra_sarrus(n):
    #arr = np.random.randint(1, n, size=(3, 3))
    arr = np.array([1,5,-2,8,3,0,4,-1,2]).reshape(3,3)
    calc = np.linalg.det(arr)
    return arr, print(f'O valor determinate da matriz = {calc}')


regra_sarrus(arr)

O valor determinate da matriz = -33.99999999999999


(array([[ 1,  5, -2],
        [ 8,  3,  0],
        [ 4, -1,  2]]),
 None)

In [75]:
def determinante(arr):
    
    #declarar cada posição da matriz em variaveis
    a,b,c =(0,0),(0,1),(0,2)
    d,e,f =(1,0),(1,1),(1,2)
    g,h,i =(2,0),(2,1),(2,2)
    #calculo conforme descrição do exercício
    detp = (arr[a]*arr[e]*arr[i]) + (arr[b]*arr[f]*arr[g]) + (arr[c]*arr[d]*arr[h])
    dets = (arr[a]*arr[f]*arr[h]) + (arr[b]*arr[d]*arr[i]) + (arr[c]*arr[e]*arr[g])

    return detp-dets
arr = np.array([1,5,-2,8,3,0,4,-1,2]).reshape(3,3)
determinante(arr)

-34